In [2]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.patheffects as path_effects
%pylab

plt.clf()
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
gs = GridSpec(2, 7)
fig = plt.gcf()
fig.set_tight_layout({'pad':0})
fig.set_size_inches((5.375, 2.75))


Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [3]:
ax0 = plt.subplot(gs[0, :3])
plt.axis('off')



(0.0, 1.0, 0.0, 1.0)

In [4]:
ax1 = plt.subplot(gs[1, :3])

## Paulsson Predictions
kI, gamma,KI,eps,rho = 1,log(2)/30.,0.95,0.545,0.65 # Params from paulsson paper

#ax1.fill_between([0, 1.5], [1,1], [0,0], color='#f0f0f0')   
for gamma in [log(2)/30.]:

    kp = np.linspace(0.05,1-0.0000001,1000)
    #ax1 = fig.add_subplot(Grid[0:4,5:10])
    ax1.plot(kp/kI,(eps+gamma)/(kI-kp)*(rho*(kp/gamma)-1)*KI,color='#cc333f', lw = 0.5)
    ax1.text(kp[400]/kI, (eps+gamma)/(kI-kp[400])*(rho*(kp[400]/gamma)-1)*KI*1.2, 
             'hyperbolic (n=1)', fontsize=5, rotation=27, ha='center', va='center', color='#cc333f',
             bbox=dict(boxstyle="round4,pad=0.2, rounding_size=0.2", facecolor='None', alpha=1, lw=0))
    ax1.semilogy(kp/kI, (eps+gamma)/(kI-kp)*log(rho*(kp/gamma))*KI, color='#231f20', lw=0.5)
    ax1.text(kp[550]/kI,  (eps+gamma)/(kI-kp[550])*log(rho*(kp[550]/gamma))*KI*1.2, 
             'exponential (n=∞)', fontsize=5, rotation=20, ha='center', va='center', color='#231f20',
             bbox=dict(boxstyle="round4,pad=0.2, rounding_size=0.2", facecolor='None', alpha=1, lw=0))  
    ax1.fill_between(kp/kI, 
                     (eps+gamma)/(kI-kp)*(rho*(kp/gamma)-1)*KI, 
                     (eps+gamma)/(kI-kp)*log(rho*(kp/gamma))*KI, 
                     color='#4682b4', alpha=0.25)
    tt = ax1.text(kp[550]/kI,  (eps+gamma)/(kI-kp[550])*log(rho*(kp[550]/gamma))*KI*2.5, 
                  'stable plasmid copy number', fontweight='light', fontsize=5, rotation=25, ha='center', 
                  va='center', color='#335266',
                  bbox=dict(boxstyle="round4,pad=0.2, rounding_size=0.2", facecolor='None', alpha=1, lw=0))  
#tt.set_path_effects([path_effects.Stroke(linewidth=0.25, foreground='#335266'),
#                       path_effects.Normal()])

ax1.plot([0, 1.5], [1,1], color='#ffffff', lw=1, dashes=(1.5,1.5), alpha=0.8)  
ax1.plot([0, 1.5], [1,1], color='#231f20', lw=0.5, dashes=(3,3))  

#ax1.fill_between([1, 2], [10000,10000], [0.001,0.001], color='#f0f0f0') 
ax1.plot([1, 1], [0.01,10000], color='#ffffff', lw=1, dashes=(1.5, 1.5), alpha=0.8)  
ax1.plot([1, 1], [0.01,10000], color='#231f20', lw=0.5, dashes=(3,3))  

bbox_props = dict(boxstyle="round,pad=0.25", fc="#f3f5f7", ec="#231f20", lw=0.25)
ax1.text(0.55, 0.475, "Plasmid loss", ha="center", va="center", rotation=0,
            size=7,
            bbox=bbox_props)

bbox_props = dict(boxstyle="rarrow,pad=0.25", fc="#f3f5f7", ec="#231f20", lw=0.25)
ax1.text(1.115, 50, "Runaway replication", ha="center", va="center", rotation=90,
            size=7,
            bbox=bbox_props)



xlim((0, 1.25))    
ylim((0.2, 3500))
#ax1.set_yscale('log')
ax1.set_xlabel(r'RNA production ratio $\left(\dfrac{k_p}{k_i}\right)$')
ax1.set_ylabel('Plasmid Copy Number')
ax1.tick_params(which = 'both', axis = 'both')
ax1.set_yticks([1, 10, 100, 1000])
ax1.get_yaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())


axin1 = ax1.inset_axes([0.1875, 0.65, 0.4, 0.30])
kp = 0.5
gamma = linspace(log(2)/120, log(2)/2, 1000)
#ax1 = fig.add_subplot(Grid[0:4,5:10])
axin1.plot(log(2)/gamma,(eps+gamma)/(kI-kp)*(rho*(kp/gamma)-1)*KI,color='#cc333f', lw = 0.5)
#n=0.5
#axin1.plot(log(2)/gamma,(eps+gamma)/(kI-kp)*((rho*(kp/gamma))**(1./n)-1)*KI*n,color='#35aaaf', lw = 0.5)
axin1.semilogy(log(2)/gamma, (eps+gamma)/(kI-kp)*log(rho*(kp/gamma))*KI, color='#231f20', lw=0.5)
axin1.fill_between(log(2)/gamma, 
                   (eps+gamma)/(kI-kp)*log(rho*(kp/gamma))*KI, 
                   (eps+gamma)/(kI-kp)*(rho*(kp/gamma)-1)*KI, 
                   color='#4682b4', alpha=0.25)

axin1.set_ylim((0.33, 250))
axin1.set_xlim((-1, 120))
axin1.set_xlabel('Division time', fontsize=5)
axin1.set_ylabel('PCN', fontsize=5)
axin1.set_xticks([0, 60, 120])
axin1.set_yticks([1, 10, 100])
axin1.tick_params(labelsize=5)
axin1.get_yaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())
axin1.tick_params(top=True, right=True)
axin1.text(10, 75, r'$k_p=0.5$', fontsize=4)
axin1.spines['right'].set_visible(True)
axin1.spines['top'].set_visible(True)
#axin1.fill_between(kp/kI, (eps+gamma)/(kI-kp)*(rho*(kp/gamma)-1)*KI, (eps+gamma)/(kI-kp)*log(rho*(kp/gamma))*KI, color='#4682b4')


In [5]:
ax3 = plt.subplot(gs[0, 3:5])

atc = [100,10,3,1,0.3,0.1,0.01,0.001]
pcn = [49.6363636363636,40.921052631579,42.5,46.1290322580645,32.8358208955224,11.2641509433962,2.8433734939759,1.46987951807229]
low = [36.0810810810811, 30.3, 32.0192307692308, 34.0243902439024,24.48275862068978,14.5555555555556,2.02803738317757,1.03809523809524]
high = [62.3913043478261,50,50.7142857142857,56.6037735849057,40,3.73972602739726,2.06849315068493,1.03809523809524]
error = np.zeros((2,len(pcn)))
for i in range(0,len(pcn)):
    error[0][i] = abs(high[i] - pcn[i])
    error[1][i] = abs(pcn[i] - low[i])

    

f= polyfit(log(atc[:-3]), log(pcn[:-3]), 1)

ax3.errorbar(atc,pcn,yerr=error,fmt='o',ms=3.0,mew=0.5, mec='#231f20', ecolor='#231f20',color='#edf291',capsize=1)
#ax3.set_xscale('log')
#ax.set_xlabel('aTc conc (ng/ul)', fontsize=8)
#ax.set_ylabel('Plasmid Copy Number', fontsize=8)

#ax3.errorbar(atc,atcPCN, fmt='o',ms = 3, mfc='#edf291', mew = 0.5, mec = '#231f20',yerr = atcPCNerr, ecolor = '#231f20', capsize = 1)
#ax3.plot([2, 2], [0, 150], color='#ffffff', lw=1, dashes=(1.5,1.5), alpha=0.8)  
#ax3.plot([2, 2], [0, 150], color='#231f20', lw=0.5, dashes=(3,3), alpha=0.8)  


ax3.set_ylim((0.75, 200))

ax3.set_xlabel('aTc Concentration (ng/ml)')
ax3.set_ylabel('Plasmid Copy Number')
ax3.set_xscale('log')
ax3.set_yscale('log')
plt.xticks([100,10,1,0.1,0.01,0.001],['100','10','1','0.1','0.01','0'])


ax3.set_yticks([1, 10, 100])

ax3.get_yaxis().set_major_formatter(matplotlib.ticker.ScalarFormatter())

ax3.tick_params(which='major',axis='both')




In [6]:
OD = open('RawData/pUC-pTet-growth.csv','r') 

def parse(file):
    results = []
    for i in range(0,6):
        results.append([])
        for j in range(0,10):
            results[i].append([])
    for line in file:
        l = line.strip().split(',')
        for i in range(0,60):
            results[i%6][int(i/6)].append(float(l[i])-0.084)
    return results
ODs = parse(OD)

ax4 = plt.subplot(gs[0, 5:])
atc = array(([10,3,1,0.3,0.1,0.03,0.01, 0.003, 0.001, 0.0003, 0.0001]))*42 #Atc concentration

colors = ['#000fff','#150eeb','#2b0cd7','#400bc3','#550aaf','#6a099b','#800887','#950673','#aa055f','#bf044b','#d40237','#ea0123','#ff000f']

from matplotlib.colors import rgb_to_hsv, hsv_to_rgb, hex2color

colorsHSV = []
for c in colors:
    h = rgb_to_hsv(hex2color(c))
    h[2] = 0.8
    colorsHSV.append(hsv_to_rgb(h))
    print(colorsHSV[-1])

#Old values
#pcn = [40.921052631579,42.5,46.1290322580645,32.8358208955224,11.2641509433962,5.0, 2.8433734939759,2.0, 1.46987951807229, 1.2, 1]
#GR = [0.99, 1.005, 1, 1.0227, 0.978, 1, 1.065, 1.043, 1.02, 1.041, 1.14]
#GRe = [0.025, 0.025, 0.025, 0.025, 0.0375, 0.0425, 0.025, 0.03, 0.045, 0.05, 0.0475]

pcn = [49.6363636363636, 40.921052631579, 42.5, 46.1290322580645, 32.8358208955224, 11.2641509433962, 7, 2.8433734939759, 2.1, 1.46987951807229]
GR = [0.0025833333333333337, 0.002729166666666668, 0.0027083333333333347, 0.002812500000000002, 0.0028541666666666676, 0.002895833333333335, 0.002937500000000002, 0.002875000000000002, 0.002916666666666667, 0.0031250000000000023]
GRe = [9.316949906249209e-05, 8.589803386703474e-05, 0.00011785113019775914, 0.00011967838846954328, 0.00016796370308955433, 0.00011219093348196877, 0.00013975424859373776, 0.00014433756729740707, 0.000186338998124982, 0.00010206207261596584]

for i in range(len(pcn)):
    #ax4.plot(pcn[i], array(GR), marker='o',ms = 3, mfc='#efefef', mew = 0.5, mec = '#231f20', lw=0)
    ax4.errorbar(pcn[i],8*array(GR)[i], yerr = 8*array(GRe)[i],  fmt='o',ms = 2.5, mfc=colorsHSV[i], mew = 0.5, mec = '#231f20',ecolor = '#231f20', capsize = 1)


ax4.set_xlabel('Copy number')
ax4.set_ylabel('Growth rate (1/min)')
ax4.set_xscale('log')
ax4.set_ylim((0.000625, 0.03125))
plt.xticks([1, 10, 100],[1, 10, 100])

axin4 = ax4.inset_axes([0.5, 0.2, 0.4, 0.35])

atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001]
pcn = [49.6363636363636,40.921052631579,42.5,46.1290322580645,32.8358208955224,11.2641509433962,7,2.8433734939759,(2.1),1.46987951807229]
time = np.arange(0,3*len(ODs[0][0]),3)

    

b = np.zeros((6,10))
density,dsd = np.zeros(10),np.zeros(10)
for i in [2,3]:
    for j in range(0,3):
        a = np.zeros(len(ODs[i][j]))
        #for k in range(0,len(ODs[i][j])):
        #    a[k] = np.mean([ODs[i][j][k],ODs[i+1][j][k],ODs[i+2][j][k],ODs[i+3][j][k],ODs[i+4][j][k],ODs[i+5][j][k]])
   
        axin4.plot(time/20,ODs[i][j],'.',ms=0.25, color = colorsHSV[3:][j], alpha=0.125) #label=str(pcn[j])[0:4]
        #ax.plot(time, a,'-', color=colorsHSV[2:][j])
        b[i][j] = max(ODs[i][j])
        
axin4.set_xlabel('Time (mins)', fontsize=5)
axin4.set_ylabel('OD_600', fontsize=5)
axin4.set_xticks([0, 60, 120])
axin4.set_yticks([0, 1])
axin4.tick_params(labelsize=5)

[0.         0.04705882 0.8       ]
[0.07148936 0.04765957 0.8       ]
[0.16       0.04465116 0.8       ]
[0.2625641  0.04512821 0.8       ]
[0.38857143 0.04571429 0.8       ]
[0.54709677 0.04645161 0.8       ]
[0.75851852 0.04740741 0.8       ]
[0.8        0.03221477 0.61744966]
[0.8        0.02352941 0.44705882]
[0.8        0.01675393 0.31413613]
[0.8        0.00754717 0.20754717]
[0.8        0.0034188  0.11965812]
[0.8        0.         0.04705882]


In [89]:
ax5 = plt.subplot(gs[1, 3:5])

## Measuring DNA concentrations shows clear differences in ratio...time to do ddPCR experiments
meancc = np.zeros(6)
sdcc = np.zeros(6)
bla = [9460,7000,2360,3820,3940,1150]
dxs = [34,38,13.4,44,36,34]
sd = np.zeros(6)
for i in range(0,6):
    sd[i] = (np.sqrt(bla[i])+bla[i])/(dxs[i]-np.sqrt(dxs[i])) - bla[i]/dxs[i]
    sd[i] = bla[i]/dxs[i]*sqrt(1/bla[i]+1/dxs[i])
print(sd)
IPTG = [0.00001,0.001,0.01,0.03,0.1,1]
pcn = np.zeros(6)
for i in range(0,6):
    pcn[i] = bla[i]/dxs[i]
ax5.errorbar(IPTG,pcn,yerr=sd,fmt='o',ms=3,mfc='#92d8f4', mew=0.5,mec='#231f20',ecolor='#231f20',capsize=1)
ax5.plot([0.000001, 10], [270, 270], color='#ffffff', lw=1, dashes=(1.5,1.5), alpha=0.8)  
ax5.plot([0.000001, 10], [270, 270], color='#231f20', lw=0.5, dashes=(3,3), alpha=0.8)  
ax5.text(0.000025, 275, 'pUC19\ncopy number', fontsize=4)

ax5.set_xscale('log')
plt.xticks([0.00001, 0.0001, 0.01, 1], [0, 0.0001, 0.01, 1])
plt.yticks([30, 100, 200, 300])
ax5.set_ylim(9, 350)
ax5.set_xlim(0.000003, 3)
#ax2.set_yscale('log')
ax5.set_ylabel('Plasmid Copy Number')
ax5.set_xlabel('IPTG Concentration (mM)')

[47.80263166 29.9638943  48.24855076 13.16349539 18.32388458  5.88581213]


Text(0.5, 0, 'IPTG Concentration (mM)')

In [90]:
ax6 = plt.subplot(gs[1, 5:])


OD = open('RawData/pUC-pLac-RNAi-g.csv','r') 

def parse(file):
    results = []
    for i in range(0,6):
        results.append([])
        for j in range(0,6):
            results[i].append([])
    for line in file:
        l = line.strip().split(',')
        for i in range(0,36):
            results[int(i%6)][int(i/6)].append(float(l[i])-0.08)
    return results
ODs = parse(OD)


GRarr = np.zeros((6,6,len(ODs[0][0])))


for i in range(0,6):
    for j in range(0,6):
        for k in range(0,len(ODs[i][j])-1,1):
            GRarr[i][j][k] = ((ODs[i][j][k+1] - ODs[i][j][k]))
growthRate = np.zeros((6,6))


flu = np.zeros((6,6))
time = np.arange(0,400)
tmax = np.zeros((6,6))
for i in range(0,6,1):
    for j in range(0,6):
        for k in range(4,len(GRarr[i][j])):
            if GRarr[i][j][k] >= max(GRarr[i][j][k+1:]) and GRarr[i][j][k] >= max(GRarr[i][j][:k]):
                tmax[i][j] = k
                break

for i in range(0,6,1):
    for j in range(0,6):
        a = np.zeros(len(GRarr[i][j]))
        for k in range(0,len(GRarr[i][j])):
            a[k] = GRarr[i][j][k]/ODs[i][j][k]
        fg = int(tmax[i][j])
        growthRate[i][j] = log(2)/np.mean(GRarr[i][j][fg-1:fg+1])/100*40# /np.mean(ODs[i][j][f-2:f+2])

growthRate = np.transpose(growthRate)
grav = np.zeros(6)
grsd = np.zeros(6)

colors = ['#000fff',
          #'#150eeb',
          '#2b0cd7',
          #'#400bc3',
          '#550aaf',
          #'#6a099b',
          #'#800887',
          #'#950673',
          #'#aa055f',
          '#bf044b',
          '#d40237',
          #'#ea0123',
          '#ff000f']

for i in range(0,6):
    gg0 = growthRate[i]
    gg = gg0[~isinf(gg0) & (gg0>0) & (gg0<200)]
    grav[i] = log(2)/np.mean(gg)
    grsd[i] = np.std(log(2)/gg)/sqrt(len(gg))
for i in range(len(pcn)):
    ax6.errorbar(pcn[i],grav[i],yerr=grsd[i],xerr=sd[i],fmt='o',ms=3,mew=0.5,mfc=colors[i],mec='#231f20', capsize=1, ecolor='#231f20')

ax6.set_ylabel('Growth Rate (1/min)')
ax6.set_xlabel('Copy Number')
ax6.set_ylim(0., 0.02225)
ax6.set_xlim((15, 350))
plt.xticks([30, 100, 200, 300])
#ax6.set_xscale('log')

<ipython-input-90-9237e189261d>:46: RuntimeWarning: divide by zero encountered in double_scalars
  growthRate[i][j] = log(2)/np.mean(GRarr[i][j][fg-1:fg+1])/100*40# /np.mean(ODs[i][j][f-2:f+2])


([<matplotlib.axis.XTick at 0x7f861c433d90>,
 <a list of 4 Text major ticklabel objects>)

In [91]:
axin6 = ax6.inset_axes([0.5, 0.2, 0.4, 0.25])
axin6.set_xlabel('Time (mins)', fontsize=5, labelpad=0)
axin6.set_ylabel('OD 600', fontsize=5, labelpad=0)
axin6.set_xticks([0, 300, 600])
#axin3.set_yticks([0, 0.5, 1])
axin6.set_ylim(0, 1)
axin6.tick_params(labelsize=5)

colors = ['#000fff','#150eeb','#2b0cd7','#400bc3','#550aaf','#6a099b','#800887','#950673','#aa055f','#bf044b','#d40237','#ea0123','#ff000f']

cc = np.zeros((6,6))
l = ['1x','0.01x','0x,']
time = np.arange(0,3*len(ODs[0][0]),3)
for i in range(0,6,1):
    for j in range(0,6):
        a = np.zeros(len(ODs[i][j]))
        b = np.zeros(len(ODs[i][j]))
        for k in range(0,len(ODs[i][j])):
            a[k] = ODs[i][j][k]#,ODs[i+2][j][k],ODs[i+1][j][k],ODs[i+3][j][k],ODs[i+4][j][k],ODs[i+5][j][k]])
            b[k] = 0#np.std([ODs[i][j][k],ODs[i+1][j][k],ODs[i+2][j][k],ODs[i+3][j][k],ODs[i+4][j][k],ODs[i+5][j][k]])/6
        axin6.plot(time/2,a,lw=0.25,color = colors[j*2])
        cc[i][j] = max(ODs[i][j])
#axin3.legend()
axin6.set_xlim(0, 600)
axin6.set_yticks([0, 1])

In [92]:
plt.tight_layout()
fig = plt.gcf()
fig.set_tight_layout({'pad':2})
fig.set_size_inches((5.75, 3.25))
plt.savefig('Fig1-Temp.pdf')
plt.savefig('Fig1.svg')

In [82]:
grav

array([0.01545083, 0.02024353, 0.02032307, 0.01197835, 0.0092437 ,
       0.00920514])

In [53]:
f

array([0.05113053, 3.66820498])

11