In [190]:
%pylab
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
from matplotlib.gridspec import GridSpec
gs = GridSpec(2, 2)
fig = plt.gcf()
fig.set_tight_layout({'pad':2})
fig.set_size_inches((3.5, 3.5))


Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


/Users/guillaume/opt/anaconda3/lib/python3.8/site-packages/IPython/core/magics/pylab.py:159: UserWarning: pylab import has clobbered these variables: ['time', 'f']
`%matplotlib` prevents importing * from pylab and numpy
  warn("pylab import has clobbered these variables: %s"  % clobbered +


In [191]:
matplotlib.rc_file('matplotlibrc')


In [192]:
OD = open('RawData/pTet-GFP-H-IPTG-OD.csv','r') 
GFP = open('RawData/pTet-GFP-H-IPTG-GFP.csv','r')

def parse(file):
    results = []
    for i in range(0,6):
        results.append([])
        for j in range(0,10):
            results[i].append([])
    for line in file:
        l = line.strip().split(',')
        for i in range(0,60):
            results[i%6][int(i/6)].append(float(l[i])-0.08)
    return results
ODs = parse(OD)
fluor = parse(GFP)


#fig,ax = plt.subplots(figsize=(4,3))
atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0]
pcn = [49.6363636363636,40.921052631579,42.5,46.1290322580645,32.8358208955224,11.2641509433962,7,2.8433734939759,(2.1),1.46987951807229]
time = np.arange(0,3*len(ODs[0][0]),3)
colors = ['#000fff','#150eeb','#2b0cd7','#400bc3','#550aaf','#6a099b','#800887','#950673','#aa055f','#bf044b','#d40237','#ea0123','#ff000f']

'''
for i in range(0,6,6):
    for j in range(0,10):
        a = np.zeros(len(ODs[i][j]))
        b = np.zeros(len(ODs[i][j]))
        c = np.zeros(len(ODs[i][j]))
        d = np.zeros(len(ODs[i][j]))
        for k in range(0,len(ODs[i][j])):
            a[k] = np.mean([ODs[i][j][k],ODs[i+1][j][k],ODs[i+2][j][k],ODs[i+3][j][k],ODs[i+4][j][k],ODs[i+5][j][k]])
            b[k] = np.mean([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]]) - 25.0
            d[k] = np.mean([fluor[i][j][k]/ODs[i][j][k],fluor[i+1][j][k]/ODs[i+1][j][k],fluor[i+2][j][k]/ODs[i+2][j][k],fluor[i+3][j][k]/ODs[i+3][j][k],fluor[i+4][j][k]/ODs[i+4][j][k],fluor[i+5][j][k]/ODs[i+5][j][k]])
            c[k] = np.std([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]])#np.std([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]])
        ax.errorbar(a,b,yerr=c,fmt ='o',label=str(pcn[j])[0:4],capsize=2,color = colors[3:][j])
ax.set_yscale('log')
ax.legend()
ax.set_ylim([1.0,5*10**4])
ax.set_xlabel('Optical Density', fontsize = 8)
ax.set_ylabel('Fluor (AU)', fontsize=8)
fig.savefig('pTet-IPTG-curves-OD.png')
'''

"\nfor i in range(0,6,6):\n    for j in range(0,10):\n        a = np.zeros(len(ODs[i][j]))\n        b = np.zeros(len(ODs[i][j]))\n        c = np.zeros(len(ODs[i][j]))\n        d = np.zeros(len(ODs[i][j]))\n        for k in range(0,len(ODs[i][j])):\n            a[k] = np.mean([ODs[i][j][k],ODs[i+1][j][k],ODs[i+2][j][k],ODs[i+3][j][k],ODs[i+4][j][k],ODs[i+5][j][k]])\n            b[k] = np.mean([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]]) - 25.0\n            d[k] = np.mean([fluor[i][j][k]/ODs[i][j][k],fluor[i+1][j][k]/ODs[i+1][j][k],fluor[i+2][j][k]/ODs[i+2][j][k],fluor[i+3][j][k]/ODs[i+3][j][k],fluor[i+4][j][k]/ODs[i+4][j][k],fluor[i+5][j][k]/ODs[i+5][j][k]])\n            c[k] = np.std([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]])#np.std([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]])\n        ax.errorbar(a,b,yerr=c,fmt 

In [193]:
GRarr = np.zeros((6,10,len(fluor[0][0])))
c= np.zeros((6,10,len(fluor[0][0])))
colors = ['#000fff','#150eeb','#2b0cd7','#400bc3','#550aaf','#6a099b','#800887','#950673','#aa055f','#bf044b','#d40237','#ea0123','#ff000f']
for i in range(0,6):
    for j in range(0,10):
        for k in range(0,len(ODs[i][j])-1):
            GRarr[i][j][k] = (((ODs[i][j][k+1] - ODs[i][j][k])) +(ODs[i][j][k] - ODs[i][j][k-1]))/2 #Central Difference to calculate growth rate

tmax = np.zeros((6,10))
for i in range(0,6,1):
    for j in range(0,10):
        for k in range(4,200):
            if GRarr[i][j][k] >= max(GRarr[i][j][k+1:]) and GRarr[i][j][k] >= max(GRarr[i][j][:k]):
                tmax[i][j] = k #Find time of maximum growth rate for each well
                break
growthRate = np.zeros((6,10))
flu = np.zeros((6,10))
for i in range(0,6,1):
    for j in range(0,10):
        f = int(tmax[i][j])
        if f < 10:
            f = int(tmax[i-1][j])
        flu[i][j] = (np.mean(fluor[i][j][f-4:f+4])-25.0)/np.sum(ODs[i][j][f-4:f+4]) #Find Fluor/OD at time of maximum GR
        growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1]) #Average growth rate over small window around maximum

        

In [194]:
ax1 = plt.subplot(gs[0, 1])
atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001]

for i in range(0,10):
    ax1.errorbar([atcConc[i]],np.mean(np.transpose(growthRate)[i])*35/11,yerr=np.std(np.transpose(growthRate)[i])*35/11,fmt='o',ms=3,mew=0.5,mec='#231f20', color = colors[3:][i],capsize=1)
    #Divide GR by GR of 0 atc condition, this looks better if plotted against aTc concentration
ax1.set_xscale('log') 
plt.xticks([100,10,1,0.1,0.01,0.0001],['100','10','1','0.1','0.01','0'], rotation = 0)
ax1.set_xlabel('atc Concetration (ng/uL)')
ax1.set_ylabel('Growth Rate')
ax1.set_ylim((0.015, 0.025))
ax1.set_xlim((0.00004, 200))
#fig.savefig('PCNvsGR.svg')   

(4e-05, 200.0)

In [195]:
OD = open('pTet-GFP-Glycerol-Casamino-OD.csv','r') 
GFP = open('pTet-GFP-Glycerol-Casamino-Fluor.csv','r')
ODG = open('pTet-GFP-Glucose-OD.csv','r') 
GFPG = open('pTet-GFP-Glucose-F.csv','r')
ODH = open('pTet-GFP-H-IPTG-OD.csv','r') 
GFPH = open('pTet-GFP-H-IPTG-GFP.csv','r')


def parse(file):
    results = []
    for i in range(0,6):
        results.append([])
        for j in range(0,10):
            results[i].append([])
    for line in file:
        l = line.strip().split(',')
        for i in range(0,60):
            results[i%6][int(i/6)].append((float(l[i])-0.08)*4)
    return results
ODs = parse(OD)
fluor = parse(GFP)
ODsH = parse(ODH)
fluorH = parse(GFPH)
ODsG = parse(ODG)
fluorG = parse(GFPG)


atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0]
pcn = [49.6363636363636,40.921052631579,42.5,46.1290322580645,32.8358208955224,11.2641509433962,7,2.8433734939759,(2.1),1.46987951807229]
timeG = np.arange(0,3*len(ODsG[0][0]),3)
timeH = np.arange(0,3*len(ODsH[0][0]),3)
time = np.arange(0,3*len(ODs[0][0]),3)
colors = ['#000fff','#150eeb','#2b0cd7','#400bc3','#550aaf','#6a099b','#800887','#950673','#aa055f','#bf044b','#d40237','#ea0123','#ff000f']

## Below was for plotting OD and GFP vs Time ##

#dens = np.zeros((6,10))
#for i in range(0,6,6):
#    for j in range(0,10):
#        a,aH,aG = np.zeros(len(ODs[i][j])),np.zeros(len(ODsH[i][j])),np.zeros(len(ODsG[i][j]))
#        b,bH,bG = np.zeros(len(ODs[i][j])),np.zeros(len(ODsH[i][j])),np.zeros(len(ODsG[i][j]))
#        c = np.zeros(len(ODs[i][j]))
#        d = np.zeros(len(ODs[i][j]))
#        for k in range(0,len(ODs[i][j])):
#            a[k] = np.mean([ODs[i][j][k],ODs[i+1][j][k],ODs[i+2][j][k],ODs[i+3][j][k],ODs[i+4][j][k],ODs[i+5][j][k]])
#            b[k] = np.mean([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]]) - 25.0
#            d[k] = np.mean([fluor[i][j][k]/ODs[i][j][k],fluor[i+1][j][k]/ODs[i+1][j][k],fluor[i+2][j][k]/ODs[i+2][j][k],fluor[i+3][j][k]/ODs[i+3][j][k],fluor[i+4][j][k]/ODs[i+4][j][k],fluor[i+5][j][k]/ODs[i+5][j][k]])
#            c[k] = 0#np.std([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]])#np.std([fluor[i][j][k],fluor[i+1][j][k],fluor[i+2][j][k],fluor[i+3][j][k],fluor[i+4][j][k],fluor[i+5][j][k]])
#        for k in range(0,len(ODsH[i][j])):    
#            aH[k] = np.mean([ODsH[i][j][k],ODsH[i+1][j][k],ODsH[i+2][j][k],ODsH[i+3][j][k],ODsH[i+4][j][k],ODsH[i+5][j][k]])
#            bH[k] = np.mean([fluorH[i][j][k],fluorH[i+1][j][k],fluorH[i+2][j][k],fluorH[i+3][j][k],fluorH[i+4][j][k],fluorH[i+5][j][k]]) - 25.0
#        for k in range(0,len(ODsG[i][j])):    
#            aG[k] = np.mean([ODsG[i][j][k],ODsG[i+1][j][k],ODsG[i+2][j][k],ODsG[i+3][j][k],ODsG[i+4][j][k],ODsG[i+5][j][k]])
#            bG[k] = np.mean([fluorG[i][j][k],fluorG[i+1][j][k],fluorG[i+2][j][k],fluorG[i+3][j][k],fluorG[i+4][j][k],fluorG[i+5][j][k]]) - 20.0
#        ax.errorbar(time,a,fmt ='o',label=str(pcn[j])[0:4],capsize=2,color = colors[3:][j])
#        ax.errorbar(timeH,aH,fmt ='o',label=str(pcn[j])[0:4],capsize=2,color = 'Black')
#        ax.errorbar(timeG,aG,fmt ='o',label=str(pcn[j])[0:4],capsize=2,color = '#277ee1')
        
#ax.set_xlabel('Optical Density', fontsize = 8)
#ax.set_ylabel('Fluor (AU)', fontsize=8)
#fig.savefig('pTet-IPTG-curves-OD.png')
#fig,ax = plt.subplots()
#ax.errorbar(pcn,density,yerr=dsd,fmt='o',ms=5,mew=0.5,mec='black',ecolor='black',capsize=2)
#plt.xticks([100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001],['100','10','3','1','0.3','0.1','0.03','0.01','0.003','0'], rotation = 45, fontsize=8)
#ax.set_xlabel('atc concentration (ng/mL)')
#ax.set_ylabel('Final Density')
#ax.set_xscale('log')

In [196]:
GRarr = np.zeros((6,10,len(fluor[0][0])))
GRarrH = np.zeros((6,10,len(fluor[0][0])))
GRarrG = np.zeros((6,10,len(fluor[0][0])))
c= np.zeros((6,10,len(fluor[0][0])))
colors = ['#000fff','#150eeb','#2b0cd7','#400bc3','#550aaf','#6a099b','#800887','#950673','#aa055f','#bf044b','#d40237','#ea0123','#ff000f']
for i in range(0,6):
    for j in range(0,10):
        for k in range(0,len(ODs[i][j])-1):
            GRarr[i][j][k] = (((ODs[i][j][k+1] - ODs[i][j][k])) +(ODs[i][j][k] - ODs[i][j][k-1]))/2 #Central Difference to calculate growth rate
        for k in range(0,len(ODsH[i][j])-1):
            GRarrH[i][j][k] = (((ODsH[i][j][k+1] - ODsH[i][j][k])) +(ODsH[i][j][k] - ODsH[i][j][k-1]))/2 #Central Difference to calculate growth rate
        for k in range(0,len(ODsG[i][j])-1):
            GRarrG[i][j][k] = (((ODsG[i][j][k+1] - ODsG[i][j][k])) +(ODsG[i][j][k] - ODsG[i][j][k-1]))/2 #Central Difference to calculate growth rate

tmax, tmaxH,tmaxG = np.zeros((6,10)),np.zeros((6,10)),np.zeros((6,10))
for i in range(0,6,1):
    for j in range(0,10):
        for k in range(4,400):
            if GRarr[i][j][k] >= max(GRarr[i][j][k+1:401]) and GRarr[i][j][k] >= max(GRarr[i][j][:k]):
                tmax[i][j] = k #Find time of maximum growth rate for each well
                break
        for k in range(4,400):   
            if GRarrH[i][j][k] >= max(GRarrH[i][j][k+1:401]) and GRarrH[i][j][k] >= max(GRarrH[i][j][:k]):
                tmaxH[i][j] = k #Find time of maximum growth rate for each well
                break
        for k in range(4,119):   
            if GRarrG[i][j][k] >= max(GRarrG[i][j][k+1:120]) and GRarrG[i][j][k] >= max(GRarrG[i][j][:k]):
                tmaxG[i][j] = k #Find time of maximum growth rate for each well
                break

tlag,tlagH,tlagG = np.zeros((6,10)),np.zeros((6,10)),np.zeros((6,10))
for i in range(0,6,1):
    for j in range(0,10):
        for k in range(0,200):
            if ODs[i][j][k] >= 0.015:
                tlag[i][j] = k*3 #Find lagtime
                break
for i in range(0,6,1):
    for j in range(0,10):        
        for k in range(0,200):
            if ODsH[i][j][k] >= 0.015:
                tlagH[i][j] = k*3 #Find lagtime
                break
for i in range(0,6,1):
    for j in range(0,10):
        for k in range(0,400):
            if ODsG[i][j][k] >= 0.015:
                tlagG[i][j] = k*3 #Find lattime
                break

growthRate,growthRateH,growthRateG = np.zeros((6,10)),np.zeros((6,10)),np.zeros((6,10))
flu,fluH,fluG = np.zeros((6,10)),np.zeros((6,10)),np.zeros((6,10))
for i in range(0,6,1):
    for j in range(0,10):
        f = int(tmax[i][j])
        if f < 10:
            f = int(tmax[i-1][j])
        growthRate[i][j] = np.mean(GRarr[i][j][f-2:f+2])
        flu[i][j] = (np.mean(fluor[i][j][f-4:f+4]))*np.mean(ODs[i][j][f-4:f+4])#*growthRate[i][j]/pcn[j] # growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1])#Find Fluor/OD at time of maximum GR
        #growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1]) #Avera/pcn[j] # growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1])#Find Fluor/OD at time of maximum GR
        #growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1]) #Average growthge growth rate over small window around maximum
for i in range(0,6,1):
    for j in range(0,10):
        f = int(tmaxH[i][j])
        if f < 10:
            f = int(tmaxH[i-1][j])
        growthRateH[i][j] = np.mean(GRarrH[i][j][f-2:f+2])
        fluH[i][j] = (np.mean(fluorH[i][j][f-4:f+4])/np.mean(ODsH[i][j][f-4:f+4]))#*growthRate[i][j]/pcn[j] # growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1])#Find Fluor/OD at time of maximum GR
print(tmaxG)
for i in range(0,6,1):
    for j in range(0,10):
        f = int(tmaxG[i][j])
        if f < 10:
            f = int(tmaxG[i-1][j])
        growthRateG[i][j] = np.mean(GRarrG[i][j][f-2:f+2])
        fluG[i][j] = (np.mean(fluorG[i][j][f-4:f+4])/np.mean(ODsG[i][j][f-4:f+4]))#*growthRate[i][j]/pcn[j] # growthRate[i][j] = np.mean(GRarr[i][j][f-1:f+1])#Find Fluor/OD at time of maximum GR

[[111. 118. 107. 108. 112. 112.   4.  23.  74. 107.]
 [ 42. 104.  99. 107. 117.  20. 107. 107. 108. 118.]
 [108. 108. 109. 107. 106. 111. 108. 112. 118. 108.]
 [108. 109. 116. 113. 112. 109. 118. 106. 111.   0.]
 [118. 114.   0.  63.  67. 108. 110. 110. 108.  12.]
 [ 83. 108. 116. 117. 106.   8. 111. 112. 116. 107.]]


In [197]:
ProteinYield,ProteinYieldH ,ProteinYieldG  = np.zeros((6,10)),np.zeros((6,10)),np.zeros((6,10))
predictedPCN,predictedPCNH,predictedPCNG = np.zeros((6,10)), np.zeros((6,10)), np.zeros((6,10))
atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001]
ax = plt.subplot(gs[1, 0])

for i in range(0,6):
    for j in range(0,10):
        ProteinYield[i][j] = fluor[i][j][len(fluor[i][j])-1]/ODs[i][j][len(fluor[i][j])-1]
        ProteinYieldH[i][j] = fluorH[i][j][len(fluorH[i][j])-1]/ODsH[i][j][len(fluorH[i][j])-1]
        ProteinYieldG[i][j] = fluorG[i][j][len(fluorG[i][j])-1]/ODsG[i][j][len(fluorG[i][j])-2]
        predictedPCN[i][j] = fluor[i][j][len(fluor[i][j])-1]*(growthRate[i][j])/4.0
        predictedPCNH[i][j] = fluorH[i][j][len(fluorH[i][j])-1]*(growthRateH[i][j])/40.0
        predictedPCNG[i][j] = fluorG[i][j][len(fluorG[i][j])-1]*(growthRateG[i][j])/2.0

##The predicted PCN calculation is made to predicted the endpoints well, the error might be reduced if Idid the mean growth rate instead of each wells measurement...
for i in range(0,6):
    a = ProteinYieldG[i][6].copy()
    b = ProteinYieldG[i][7].copy()
    ProteinYieldG[i][6] = b
    ProteinYieldG[i][7] = a   ## columns 7 and 8 of m9+glucose were swapped
    
for i in range(0,10):
    ax.errorbar(atcConc[i],np.mean(np.transpose(ProteinYieldH)[i]),yerr=np.std(np.transpose(ProteinYieldH)[i]),fmt='o',ms=3,mew=0.5,mec='#231f20', mfc ='#f4ba27',color='#231f20',capsize=1)
    ax.errorbar(atcConc[i],np.mean(np.transpose(ProteinYield)[i]),yerr=np.std(np.transpose(ProteinYield)[i]),fmt='o',ms=3,mew=0.5,mec='#231f20', mfc ='#2ab992',color='#231f20',capsize=1)
    ax.errorbar(atcConc[i],np.mean(np.transpose(ProteinYieldG)[i]),yerr=np.std(np.transpose(ProteinYieldG)[i]),fmt='o',ms=3,mew=0.5,mec='#231f20', mfc = '#5b398a',color='#231f20',capsize=1)

#Last point is where label is attached
i = 9
ax.errorbar(atcConc[i]/1000,np.mean(np.transpose(ProteinYieldH)[i]),yerr=np.std(np.transpose(ProteinYieldH)[i]),fmt='o',ms=5,mew=0.5,mec='#231f20', mfc ='#f4ba27',color='#231f20',capsize=1,label = 'H Media')
ax.errorbar(atcConc[i]/1000,np.mean(np.transpose(ProteinYieldG)[i]),yerr=np.std(np.transpose(ProteinYieldG)[i]),fmt='o',ms=5,mew=0.5,mec='#231f20',  mfc ='#2ab992',color='#231f20',capsize=1,label = 'M9+Glu')
ax.errorbar(atcConc[i]/1000,np.mean(np.transpose(ProteinYield)[i]),yerr=np.std(np.transpose(ProteinYield)[i]),fmt='o',ms=5,mew=0.5,mec='#231f20', mfc = '#5b398a',color='#231f20',capsize=1, label = 'M9+Gly+CA')   

#ax.errorbar(pcn[i],np.mean(np.transpose(predictedGFP)[i]),yerr=np.std(np.transpose(ProteinYield)[i]),fmt='o',ms=5,mew=0.5,mec='black', color = colors[3:][i],capsize=2)
ax.set_yscale('log')
ax.set_ylabel('Endpoint Fluoresence (AU)')
ax.set_xlabel('aTc Conc (ng/$\mu$L)')
ax.set_xscale('log')
plt.xticks([100,10,1,0.1,0.01,0.0001],['100','10','1','0.1','0.01','0'])
plt.yticks([10**3,10**4,10**5])
plt.ylim((5*10**2, 9*10**5))
plt.xlim((0.00004, 400))
ax.legend(fontsize=5, borderpad=0.2)
#fig.savefig('EndpointFluor-fig2C.svg')

In [198]:
ax = plt.subplot(gs[1, 1])
for i in range(0,6):
    a = predictedPCNG[i][6].copy()
    b = predictedPCNG[i][7].copy()
    predictedPCNG[i][6] = b
    predictedPCNG[i][7] = a  ## columns 7 and 8 of m9+glucose were swapped
for i in range(0,10):
    ax.errorbar(atcConc[i],np.mean(np.transpose(predictedPCNH)[i]),yerr=np.std(np.transpose(predictedPCNH)[i]),fmt='o',ms=3,mew=0.5,mec='#231f20', mfc ='#f4ba27',color='#231f20',capsize=1)
    ax.errorbar(atcConc[i],np.mean(np.transpose(predictedPCNG)[i]),yerr=np.std(np.transpose(predictedPCNG)[i]),fmt='o',ms=3,mew=0.5,mec='#231f20', mfc ='#2ab992',color='#231f20',capsize=1)
    ax.errorbar(atcConc[i],np.mean(np.transpose(predictedPCN)[i]),yerr=np.std(np.transpose(predictedPCN)[i]),fmt='o',ms=3,mew=0.5,mec='#231f20', mfc = '#5b398a',color='#231f20',capsize=1)

#Last point is where label is attached
#i = 9
i = 9
ax.errorbar(atcConc[i]/1000,np.mean(np.transpose(predictedPCNH)[i]),yerr=np.std(np.transpose(predictedPCNH)[i]),fmt='o',ms=5,mew=0.5,mec='#231f20', mfc ='#f4ba27',color='#231f20',capsize=1,label = 'H Media')
ax.errorbar(atcConc[i]/1000,np.mean(np.transpose(predictedPCNG)[i]),yerr=np.std(np.transpose(predictedPCNG)[i]),fmt='o',ms=5,mew=0.5,mec='#231f20', mfc ='#2ab992',color='#231f20',capsize=1,label = 'M9+Glu')
ax.errorbar(atcConc[i]/1000,np.mean(np.transpose(predictedPCN)[i]),yerr=np.std(np.transpose(predictedPCN)[i]),fmt='o',ms=5,mew=0.5,mec='#231f20', mfc = '#5b398a',color='#231f20',capsize=1, label = 'M9+Gly+CA')    

ax.set_yscale('log')
ax.set_ylabel('Predicted PCN')
ax.set_xlabel('aTc Conc (ng/$\mu$L)')
ax.set_xscale('log')
plt.xticks([100,10,1,0.1,0.01,0.0001],['100','10','1','0.1','0.01','0'])
plt.yticks([10**0,10**1,10**2])
plt.xlim((0.00004, 400))
plt.ylim((5*10**-1, 9*10**2))
ax.legend(fontsize=5, borderpad=0.2, loc=2)

#fig.savefig('Predicted-PCN-Fig2D.svg')
#Overall - PCN appears to saturated at lower concentration but still maintains linear relationshipp.....

In [199]:

plt.tight_layout()
fig = plt.gcf()
fig.set_tight_layout({'pad':2})
fig.set_size_inches((3.5, 2.75))
plt.savefig('Fig2-New.pdf')
plt.savefig('Fig2-New.svg')


In [174]:
## Not plotting M9 measurements on this fig bc they are very far below the H media and don't change much ##

fig,ax = plt.subplots(figsize=(4,3))
from scipy.stats import hmean
atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001]
for i in range(0,6):
    a = growthRateG[i][6]
    b = growthRateG[i][7]
    growthRateG[i][6] = b
    growthRateG[i][7] = a  ## columns 7 and 8 of m9+glucose were swapped
#/np.mean(np.transpose(growthRate)[9])
for i in range(0,9):
    #ax.errorbar([atcConc[i]],hmean(np.transpose(growthRate)[i]),yerr=np.std(np.transpose(growthRate)[i]),fmt='o',ms=5,mew=0.5,mec='black', color = colors[3:][i],capsize=2)
    ax.errorbar([atcConc[i]],hmean(np.transpose(growthRateH)[i]),yerr=np.std(np.transpose(growthRateH)[i]),fmt='o',ms=8,mew=0.5,mec='black', color = 'black',capsize=2)
    #ax.errorbar([atcConc[i]],hmean(np.transpose(growthRateG)[i]),yerr=np.std(np.transpose(growthRateG)[i]),fmt='o',ms=5,mew=0.5,mec='black', color = '#277ee1',capsize=2)

i = 9
#ax.errorbar([atcConc[i]],hmean(np.transpose(growthRate)[i]),yerr=np.std(np.transpose(growthRate)[i]),fmt='o',ms=5,mew=0.5,mec='black', color = colors[3:][i],capsize=2, label='M9+Glycerol+Casamino')
ax.errorbar([atcConc[i]],hmean(np.transpose(growthRateH)[i]),yerr=np.std(np.transpose(growthRateH)[i]),fmt='o',ms=8,mew=0.5,mec='black', color = 'black',capsize=2, label = 'H Media')
#ax.errorbar([atcConc[i]],hmean(np.transpose(growthRateG)[i]),yerr=np.std(np.transpose(growthRateG)[i]),fmt='o',ms=5,mew=0.5,mec='black', color = '#277ee1',capsize=2, label = 'M9+Glucose')


ax.set_xscale('log') 
ax.legend()
plt.xticks([100,10,1,0.1,0.01,0.0001],['100','10','1','0.1','0.01','0'], fontsize=12)
plt.yticks([0.020,0.025,0.030],fontsize=12)
ax.set_xlabel('atc Concetration (ng/uL)', fontsize=18)
ax.set_ylabel('Growth Rate (1/min)',fontsize=18)
#ax.set_ylim([0.018,0.030])
fig.savefig('PCNvsGR.svg')


In [175]:
## Fold Change in mid-exponential phase, drastically reduced for m9 media

fig,ax = plt.subplots(figsize=(4,3))
atcConc = [100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001]
for i in range(0,6):
    a = fluG[i][6]
    b = fluG[i][7]
    fluG[i][6] = b ##Columns 7 and 8 were swapped##
    fluG[i][7] = a
for i in range(0,9):
    ax.errorbar([atcConc[i]],np.mean(np.transpose(flu)[i])/np.mean(np.transpose(flu)[9]),yerr=np.std(np.transpose(flu)[i])/np.mean(np.transpose(flu)[9]),fmt='o',ms=5,mew=0.5,mec='black', color = colors[3:][i],capsize=2)
    ax.errorbar([atcConc[i]],np.mean(np.transpose(fluH)[i])/np.mean(np.transpose(fluH)[9]),yerr=np.std(np.transpose(fluH)[i])/np.mean(np.transpose(fluH)[9]),fmt='o',ms=5,mew=0.5,mec='black', color = 'black',capsize=2)
    ax.errorbar([atcConc[i]],np.mean(np.transpose(fluG)[i])/np.mean(np.transpose(fluG)[0]),yerr=np.std(np.transpose(fluG)[i])/np.mean(np.transpose(fluG)[9]),fmt='o',ms=5,mew=0.5,mec='black', color = '#277ee1',capsize=2)

i = 9
ax.errorbar([atcConc[i]],np.mean(np.transpose(flu)[i])/np.mean(np.transpose(flu)[9]),yerr=np.std(np.transpose(flu)[i])/np.mean(np.transpose(flu)[9]),fmt='o',ms=5,mew=0.5,mec='black', color = colors[3:][i],capsize=2, label = 'M9+Glycerol+Casamino')
ax.errorbar([atcConc[i]],np.mean(np.transpose(fluH)[i])/np.mean(np.transpose(fluH)[9]),yerr=np.std(np.transpose(fluH)[i])/np.mean(np.transpose(fluH)[9]),fmt='o',ms=5,mew=0.5,mec='black', color = 'black',capsize=2, label = 'H Media')
ax.errorbar([atcConc[i]],np.mean(np.transpose(fluG)[i])/np.mean(np.transpose(fluG)[9]),yerr=np.std(np.transpose(fluG)[i])/np.mean(np.transpose(fluG)[9]),fmt='o',ms=5,mew=0.5,mec='black', color = '#277ee1',capsize=2, label = 'M9 + Glucose')
ax.legend()
ax.set_xscale('log')   
ax.set_yscale('log')
plt.xticks([100,10,3,1,0.3,0.1,0.03,0.01,0.003,0.0001],['100','10','3','1','0.3','0.1','0.03','0.01','0.003','0'], rotation = 45, fontsize=8)
ax.set_xlabel('atc conc (ng/uL)', fontsize=10)
ax.set_ylabel('GFP (AU)', fontsize=10)
fig.savefig('newGFP-atc-midEx.png')